services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nika-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./frontend/public/products:/frontend/public/products
      - ./данные nika:/app/данные nika:ro
      - ./новые_фото:/app/новые_фото:ro
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:Kohkau11999@postgres:5432/nika
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - nika-network

  postgres:
    image: postgres:15-alpine
    container_name: nika-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Kohkau11999
      - POSTGRES_DB=nika
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nika-network

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nika-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Маппим основной конфиг
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/public/products:/usr/share/nginx/html/products
      # Прокидываем сертификаты внутрь контейнера
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    depends_on:
      - backend
    networks:
      - nika-network

networks:
  nika-network:
    driver: bridge

volumes:
  pgdata: