services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: promsell-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./frontend/public/products:/frontend/public/products
      - ./данные promsell:/app/данные promsell:ro
      - ./новые_фото:/app/новые_фото:ro
    env_file:
      - .env
    networks:
      - promsell-network

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: promsell-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Маппим основной конфиг
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/public/products:/usr/share/nginx/html/products
      # Прокидываем сертификаты внутрь контейнера
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    depends_on:
      - backend
    networks:
      - promsell-network

networks:
  promsell-network:
    driver: bridge

